// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/hitokoto-osc/reviewer/internal/dao/internal"
)

// internalPendingDao is internal type for wrapping internal DAO implements.
type internalPendingDao = *internal.PendingDao

// pendingDao is the data access object for table hitokoto_pending.
// You can define custom methods on it to extend its functionality as you wish.
type pendingDao struct {
	internalPendingDao
}

var (
	// Pending is globally public accessible object for table hitokoto_pending operations.
	Pending = pendingDao{
		internal.NewPendingDao(),
	}
)

// Fill with you ideas below.
