// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/hitokoto-osc/reviewer/internal/dao/internal"
)

// internalPollPipelineDao is internal type for wrapping internal DAO implements.
type internalPollPipelineDao = *internal.PollPipelineDao

// pollPipelineDao is the data access object for table hitokoto_poll_pipeline.
// You can define custom methods on it to extend its functionality as you wish.
type pollPipelineDao struct {
	internalPollPipelineDao
}

var (
	// PollPipeline is globally public accessible object for table hitokoto_poll_pipeline operations.
	PollPipeline = pollPipelineDao{
		internal.NewPollPipelineDao(),
	}
)

// Fill with you ideas below.
