// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/hitokoto-osc/reviewer/internal/dao/internal"
)

// internalPollLogDao is internal type for wrapping internal DAO implements.
type internalPollLogDao = *internal.PollLogDao

// pollLogDao is the data access object for table hitokoto_poll_log.
// You can define custom methods on it to extend its functionality as you wish.
type pollLogDao struct {
	internalPollLogDao
}

var (
	// PollLog is globally public accessible object for table hitokoto_poll_log operations.
	PollLog = pollLogDao{
		internal.NewPollLogDao(),
	}
)

// Fill with you ideas below.
