// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/hitokoto-osc/reviewer/internal/dao/internal"
)

// internalPollScorePipelineDao is internal type for wrapping internal DAO implements.
type internalPollScorePipelineDao = *internal.PollScorePipelineDao

// pollScorePipelineDao is the data access object for table hitokoto_poll_score_pipeline.
// You can define custom methods on it to extend its functionality as you wish.
type pollScorePipelineDao struct {
	internalPollScorePipelineDao
}

var (
	// PollScorePipeline is globally public accessible object for table hitokoto_poll_score_pipeline operations.
	PollScorePipeline = pollScorePipelineDao{
		internal.NewPollScorePipelineDao(),
	}
)

// Fill with you ideas below.
