// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/hitokoto-osc/reviewer/internal/dao/internal"
)

// internalRefuseDao is internal type for wrapping internal DAO implements.
type internalRefuseDao = *internal.RefuseDao

// refuseDao is the data access object for table hitokoto_refuse.
// You can define custom methods on it to extend its functionality as you wish.
type refuseDao struct {
	internalRefuseDao
}

var (
	// Refuse is globally public accessible object for table hitokoto_refuse operations.
	Refuse = refuseDao{
		internal.NewRefuseDao(),
	}
)

// Fill with you ideas below.
