// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/hitokoto-osc/reviewer/internal/dao/internal"
)

// internalSentenceHistoryDao is internal type for wrapping internal DAO implements.
type internalSentenceHistoryDao = *internal.SentenceHistoryDao

// sentenceHistoryDao is the data access object for table hitokoto_sentence_history.
// You can define custom methods on it to extend its functionality as you wish.
type sentenceHistoryDao struct {
	internalSentenceHistoryDao
}

var (
	// SentenceHistory is globally public accessible object for table hitokoto_sentence_history operations.
	SentenceHistory = sentenceHistoryDao{
		internal.NewSentenceHistoryDao(),
	}
)

// Fill with you ideas below.
