// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/hitokoto-osc/reviewer/internal/dao/internal"
)

// internalUserNotificationDao is internal type for wrapping internal DAO implements.
type internalUserNotificationDao = *internal.UserNotificationDao

// userNotificationDao is the data access object for table hitokoto_user_notification.
// You can define custom methods on it to extend its functionality as you wish.
type userNotificationDao struct {
	internalUserNotificationDao
}

var (
	// UserNotification is globally public accessible object for table hitokoto_user_notification operations.
	UserNotification = userNotificationDao{
		internal.NewUserNotificationDao(),
	}
)

// Fill with you ideas below.
