name: Deploy To Dockerhub(Latest)

on:
  push:
    branches: [ main ]

jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Build
        run: mkdir -p ./temp && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags '-s -w --extldflags "-static -fpic"' -o ./temp/linux_amd64/hitokoto_reviewer main.go
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: hitokoto/reviewer:latest
          file: ./manifest/docker/Dockerfile
          context: .
